import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Code Graph - Fanspot',
  description: 'Interactive map of the Fanspot codebase generated by graphify.',
}

export default function GraphLayout({ children }: { children: React.ReactNode }) {
  return children
}
